image:
  repository: anodot/anodot-kube-events
  tag: "0.0.9"
  pullPolicy: Always

configuration:
  replicas: 1
  resources:
    requests:
      memory: '20M'
      cpu: '50m'
    limits:
      memory: '200M'
      cpu: '200m'
  env:
    ANODOT_API_TOKEN: ""
    ANODOT_URL: ""
    ANODOT_EVENT_CATEGORY: "deployments"
    ANODOT_EVENT_SOURCE: "kubernetes"
    ANODOT_LOG_LEVEL: "2"
    ANODOT_HTTP_DEBUG_ENABLED: "false"
  events:
    deployment:
      enabled: true
    statefulset:
      enabled: true
    daemonset:
      enabled: true
    job:
      enabled: true
    secret:
      enabled: true
    configmap:
      enabled: true
      exclude:
        labels:
          OWNER: "TILLER"
        annotations:
          "control-plane.alpha.kubernetes.io/leader": ".*"

livenessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 30
readinessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 30

rbac:
  enabled: true

prometheus:
  serviceMonitor:
    enabled: false
    jobLabel: "anodot-kube-events"
    #labels:
    #  key: "value"

    interval: 30s
    scrapeTimeout: 5s

    metricRelabelings: []
    #  - sourceLabels: [__name__]
    #    regex: '(.*)'
    #    targetLabel: anodot_include
    #    replacement: 'true'
    #  - sourceLabels: [__name__]
    #    regex: '(.*)'
    #    action: 'keep'
    relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   target_label: nodename
    #   replacement: $1
    #   action: replace
