apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "streamsets.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "streamsets.name" . }}
    helm.sh/chart: {{ include "streamsets.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "streamsets.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "streamsets.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "streamsets.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: streamsets
          image: "{{ .Values.streamsets.repository }}:{{ .Values.streamsets.tag }}"
          imagePullPolicy: {{ .Values.streamsets.pullPolicy }}
          {{- if .Values.streamsets.env }}
          env:
          {{- range $name, $value := .Values.streamsets.env }}
            - name: "{{ $name }}"
              value: "{{ $value }}"
          {{- end }}
          {{- end }}
          volumeMounts:
            - mountPath: /data
              name: streamsets-data
          ports:
            - name: http
              containerPort: 18630
              protocol: TCP
          livenessProbe:
              httpGet:
                path: /
                port: 18630
              initialDelaySeconds: 25
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 3
          readinessProbe:
              httpGet:
                path: /
                port: 18630
          resources:
{{ toYaml .Values.streamsets.resources | indent 12 }}
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: streamsets-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
        {{- end }}
{{- else }}
      volumes:
        - emptyDir: {}
          name: streamsets-data
{{- end }}