{{ if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: anodot-kube-events
rules:
  - apiGroups: ["*"]
    resources:
      - pods
      - replicasets
      - deployments
      - daemonsets
      - configmaps
      - daemonsets
      - jobs
      - statefulsets
      - secrets
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: anodot-kube-events
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: anodot-kube-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anodot-kube-events
subjects:
  - kind: ServiceAccount
    name: anodot-kube-events
    namespace: {{.Release.Namespace}}
{{- end }}
