apiVersion: v1
kind: Service
metadata:
  name: {{ template "template_name" . }}
  labels:
    app: {{ template "template_name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "template_name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080