# Default values for agent.
# Agent docs can be found at https://github.com/anodot/daria/wiki
replicaCount: 1

image:
  repository: anodot/daria
  tag: 3.3.1
  pullPolicy: IfNotPresent
  resources: {}
  limits:
   cpu: 1
   memory: 4Gi
  requests:
   cpu: 1
   memory: 4Gi
env:
  - name: ENV_PROD
    value: 'false'
  - name: AGENT_DB_HOST
    value: "postgres-postgresql"
  - name: AGENT_DB_USER
    value: 'agent'
  - name: AGENT_DB_PASSWORD
    value: 'agent'
  - name: AGENT_DB
    value: "postgres-postgresql"
  - name: LISTEN_PORT
    value: 8080

nameOverride: "anodot-agent"
fullnameOverride: "anodot-agent"

service:
  name: anodot-agent
  type: ClusterIP
  port: 8080

container:
  port: 8080

