apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anodot-ses-notifications.fullname" . }}
  labels:
    app: {{ include "anodot-ses-notifications.fullname" . }}
    release: {{ .Release.Name }}
data:
  config.yaml: |-
    # User-supplied configuration:
{{ toYaml .Values.configuration.file  | indent 4 }}