{{ if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    labels:
        requiredBy: anodot
        app.kubernetes.io/name: {{ include "anodot-ses-notifications.fullname" . }}
{{- if .Values.prometheus.serviceMonitor.labels}}
    {{ toYaml .Values.prometheus.serviceMonitor.labels | indent 4 }}
{{- end }}
    name: {{ include "anodot-ses-notifications.fullname" . }}
spec:
    jobLabel: {{ .Values.prometheus.serviceMonitor.jobLabel }}
    namespaceSelector:
        any: true
    selector:
        matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/name: {{ include "anodot-ses-notifications.name" . }}
    endpoints:
    - port: http
            {{- if .Values.prometheus.serviceMonitor.interval }}
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
            {{- end }}
            {{- if .Values.prometheus.serviceMonitor.metricRelabelings }}
      metricRelabelings:
{{ tpl (toYaml .Values.prometheus.serviceMonitor.metricRelabelings | indent 8) . }}
            {{- end }}
{{- if .Values.prometheus.serviceMonitor.relabelings }}
      relabelings:
{{ toYaml .Values.prometheus.serviceMonitor.relabelings | indent 8 }}
            {{- end }}
{{- end }}