image:
  repository: anodot/prometheus-remote-write
  tag: "2.3.2"
  pullPolicy: IfNotPresent

configuration:
  resources:
    requests:
      memory: '4Gi'
      cpu: '2'
    limits:
      memory: '5Gi'
      cpu: '3'
  replicas: 1
  env:
    ANODOT_LOG_LEVEL: "3"
    ANODOT_TAGS: "source=prometheus-remote-write"
    ANODOT_HTTP_DEBUG_ENABLED: "false"
    ANODOT_API_TOKEN: "CHANGE_ME"
    #K8S_RELABEL_SERVICE_URL: "http://anodot-pod-relabel:8080"
  args:
    - "--url=https://api.anodot.com"

livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 2
  periodSeconds: 30
readinessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 2
  periodSeconds: 30

service:
  type: ClusterIP

prometheus:
  serviceMonitor:
    enabled: false
    jobLabel: "anodot-prometheus-remote-write"
    #labels:
    #  key: "value"

    interval: 30s
    scrapeTimeout: 5s

    metricRelabelings: []
    #  - sourceLabels: [__name__]
    #    regex: '(.*)'
    #    targetLabel: anodot_include
    #    replacement: 'true'
    #  - sourceLabels: [__name__]
    #    regex: '(.*)'
    #    action: 'keep'
    relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   target_label: nodename
    #   replacement: $1
    #   action: replace
